"""Update impressions dtype

Revision ID: 455b47f823f8
Revises: 6bc1ca235176
Create Date: 2021-12-27 17:36:59.345424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '455b47f823f8'
down_revision = '6bc1ca235176'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
